Repository kakao-tech-campus-2nd-step3/Team3_FE, pull requests merged in 2024-11, with the labels that each got.

#49 Fix/feat/#46
  src/api/hooks/useCreatePlan.ts
  src/api/hooks/useDeleteFriend.ts
  src/api/hooks/useDeletePlan.ts
  src/api/hooks/useFriendRequest.ts
  src/api/hooks/useGetComments.ts
  src/api/hooks/useGetFriends.ts
  src/api/hooks/useUserData.ts
Labels: 🐛bug

#55 [feature]: 메인페이지, 프리뷰 플랜 페이지, 플랜 페이지 API 연동 작업 완료 (수정 사항 계속 나올듯)
  src/api/hooks/useCreatePlans.ts
  src/api/hooks/useDeletePlanCard.ts
  src/api/hooks/useGenerateDeviceId.ts
  src/api/hooks/useGetPlanCard.ts
  src/api/hooks/useGetPlans.ts
  src/api/hooks/useGptRequest.ts
  src/api/hooks/useGptTrial.ts
  src/api/hooks/useSavePlan.ts
  src/api/hooks/useSavePreviewPlan.ts
  src/api/hooks/useUpdatePlanCard.ts
  src/api/hooks/useUpdatePlans.ts
  src/components/features/CustomCalendar/CustomCalendar.tsx
  src/pages/LoginModal/RedirectPage.tsx
  src/pages/Main/MainPage.tsx
  src/pages/Plan/PlanPage.tsx
  src/pages/Plan/PlanSelectPage.tsx
  src/pages/Plan/PlanUpdate.tsx
  src/pages/PreviewPlan/PreviewPlanPage.tsx
  src/pages/PreviewPlan/PreviewPlanSelectPage.tsx
  src/pages/PreviewPlan/PreviewPlanUpdate.tsx
Labels: ✨feature

#60 chore: lint, tsc error 해결
  src/api/hooks/useCreateTeam.ts
  src/api/hooks/useGetTeamPlan.ts
  src/api/hooks/useTeamPlanSave.ts
  src/components/features/CustomCalendar/CustomCalendar.tsx
  src/components/features/CustomCalendar/PlanModal.tsx
  src/components/features/Introduce/Introduce.tsx
  src/pages/Friend/FriendPage.tsx
  src/pages/TeamPlan/TeamPlan.tsx
  src/pages/TeamPlan/TeamPlanChange.tsx
  src/pages/TeamPlan/TeamPlanMaking.tsx
  src/pages/TeamPlan/TeamPlanSelectPage.tsx
  src/pages/TeamPlan/TeamPlanUpdate.tsx
  src/provider/AuthProvider.tsx
Labels: 🐛bug

#61 chore: tsc오류수정
  src/pages/TeamPlan/TeamPlanMaking.tsx
Labels: 🐛bug

#64 [feature]: 디자인 수정, 기능 수정
  .env.development
  package.json
  public/mockServiceWorker.js
  src/api/hooks/useGenerateDeviceId.ts
  src/api/hooks/useGetPlanCard.ts
  src/api/hooks/useSavePlan.ts
  src/api/hooks/useUpdatePlan.ts
  src/assets/kakao_logo.svg
  src/components/common/Button/StyledButton.styles.ts
  src/components/common/Sidebar/Sidebar.tsx
  src/components/features/CustomCalendar/CustomCalendar.tsx
  src/components/features/Introduce/Introduce.tsx
  src/pages/Friend/FriendPage.tsx
  src/pages/LoginModal/RedirectPage.tsx
  src/pages/Main/MainPage.tsx
  src/pages/Mypage/Mypage.tsx
  src/pages/Plan/PlanPage.tsx
  src/pages/Plan/PlanSelectPage.tsx
  src/pages/Plan/PlanUpdate.tsx
  src/pages/PreviewPlan/PreviewPlanPage.tsx
  src/pages/PreviewPlan/PreviewPlanSelectPage.tsx
  src/pages/PreviewPlan/PreviewPlanUpdate.tsx
  src/pages/TeamPlan/TeamPlan.tsx
  src/pages/TeamPlan/TeamPlanChange.tsx
  src/pages/TeamPlan/TeamPlanDetail.tsx
  src/pages/TeamPlan/TeamPlanSelectPage.tsx
Labels: ✨feature

#66 [merge]: 10주차 개발 master 에 병합
  .env.development
  package-lock.json
  package.json
  public/mockServiceWorker.js
  src/api/hooks/useCreateTeam.ts
  src/api/hooks/useDeletePlanCard.ts
  src/api/hooks/useDeleteTeamPlan.ts
  src/api/hooks/useFriendRequest.ts
  src/api/hooks/useGenerateDeviceId.ts
  src/api/hooks/useGetPlanCard.ts
  src/api/hooks/useGetPlans.ts
  src/api/hooks/useGetTeamPlan.ts
  src/api/hooks/useGptRequest.ts
  src/api/hooks/useGptTrial.ts
  src/api/hooks/useSavePlan.ts
  src/api/hooks/useSavePreviewPlan.ts
  src/api/hooks/useTeam.ts
  src/api/hooks/useTeamPlan.ts
  src/api/hooks/useTeamPlanSave.ts
  src/api/hooks/useUpdatePlan.ts
  src/api/hooks/useUpdatePlanCard.ts
  src/api/hooks/useUpdatePlans.ts
  src/api/hooks/useUpdateTeamPlan.ts
  src/assets/kakao_logo.svg
  src/assets/kakao_symbol.svg
  src/components/common/Button/StyledButton.styles.ts
  src/components/common/Modal/Modal.tsx
  src/components/common/Sidebar/Sidebar.tsx
  src/components/features/CustomCalendar/CustomCalendar.tsx
  src/components/features/CustomCalendar/PlanModal.tsx
  src/components/features/Introduce/Introduce.tsx
  src/pages/Friend/FriendDetailPage.tsx
  src/pages/Friend/FriendPage.tsx
  src/pages/LoginModal/RedirectPage.tsx
  src/pages/Main/MainPage.tsx
  src/pages/Mypage/Mypage.tsx
  src/pages/Plan/PlanPage.tsx
  src/pages/Plan/PlanSelectPage.tsx
  src/pages/Plan/PlanUpdate.tsx
  src/pages/PreviewPlan/PreviewPlanPage.tsx
  src/pages/PreviewPlan/PreviewPlanSelectPage.tsx
  src/pages/PreviewPlan/PreviewPlanUpdate.tsx
  src/pages/TeamPlan/TeamPlan.tsx
  src/pages/TeamPlan/TeamPlanChange.tsx
  src/pages/TeamPlan/TeamPlanDetail.tsx
  src/pages/TeamPlan/TeamPlanInvite.tsx
  src/pages/TeamPlan/TeamPlanMaking.tsx
  src/pages/TeamPlan/TeamPlanSelectPage.tsx
  src/pages/TeamPlan/TeamPlanUpdate.tsx
  src/pages/TeamPlan/TeamPlanUpdatePage.tsx
  src/provider/AuthProvider.tsx
  src/router/Router.tsx
  src/router/RouterPath.ts
  src/types/types.ts
Labels: 🔄merge

#67 [review] 10주차 코드리뷰
  .env.development
  package-lock.json
  package.json
  public/mockServiceWorker.js
  src/api/hooks/useCreateTeam.ts
  src/api/hooks/useDeletePlanCard.ts
  src/api/hooks/useDeleteTeamPlan.ts
  src/api/hooks/useFriendRequest.ts
  src/api/hooks/useGenerateDeviceId.ts
  src/api/hooks/useGetPlanCard.ts
  src/api/hooks/useGetPlans.ts
  src/api/hooks/useGetTeamPlan.ts
  src/api/hooks/useGptRequest.ts
  src/api/hooks/useGptTrial.ts
  src/api/hooks/useSavePlan.ts
  src/api/hooks/useSavePreviewPlan.ts
  src/api/hooks/useTeam.ts
  src/api/hooks/useTeamPlan.ts
  src/api/hooks/useTeamPlanSave.ts
  src/api/hooks/useUpdatePlan.ts
  src/api/hooks/useUpdatePlanCard.ts
  src/api/hooks/useUpdatePlans.ts
  src/api/hooks/useUpdateTeamPlan.ts
  src/assets/kakao_logo.svg
  src/assets/kakao_symbol.svg
  src/components/common/Button/StyledButton.styles.ts
  src/components/common/Modal/Modal.tsx
  src/components/common/Sidebar/Sidebar.tsx
  src/components/features/CustomCalendar/CustomCalendar.tsx
  src/components/features/CustomCalendar/PlanModal.tsx
  src/components/features/Introduce/Introduce.tsx
  src/pages/Friend/FriendDetailPage.tsx
  src/pages/Friend/FriendPage.tsx
  src/pages/LoginModal/RedirectPage.tsx
  src/pages/Main/MainPage.tsx
  src/pages/Mypage/Mypage.tsx
  src/pages/Plan/PlanPage.tsx
  src/pages/Plan/PlanSelectPage.tsx
  src/pages/Plan/PlanUpdate.tsx
  src/pages/PreviewPlan/PreviewPlanPage.tsx
  src/pages/PreviewPlan/PreviewPlanSelectPage.tsx
  src/pages/PreviewPlan/PreviewPlanUpdate.tsx
  src/pages/TeamPlan/TeamPlan.tsx
  src/pages/TeamPlan/TeamPlanChange.tsx
  src/pages/TeamPlan/TeamPlanDetail.tsx
  src/pages/TeamPlan/TeamPlanInvite.tsx
  src/pages/TeamPlan/TeamPlanMaking.tsx
  src/pages/TeamPlan/TeamPlanSelectPage.tsx
  src/pages/TeamPlan/TeamPlanUpdate.tsx
  src/pages/TeamPlan/TeamPlanUpdatePage.tsx
  src/provider/AuthProvider.tsx
  src/router/Router.tsx
  src/router/RouterPath.ts
  src/types/types.ts
Labels: 💬review

#73 [feature] : 최종
  .eslintrc.cjs
  dist/assets/index-DNagE171.js
  dist/assets/index-KWo6zzW6.css
  dist/assets/logo-CmO4ZKwy.svg
  dist/assets/mock2-BvRgIRQl.svg
  dist/assets/step1-DsUboUzH.svg
  dist/assets/step2-CJ8X2DvV.svg
  dist/assets/step3-DSVRkaDE.svg
  dist/index.html
  index.html
  package-lock.json
  package.json
  public/firebase-messaging-sw.js
  src/api/firebaseConfig.ts
  src/api/hooks/useCreatePlan.ts
  src/api/hooks/useFcmOffsetUpdate.ts
  src/api/hooks/useFcmUpdate.ts
  src/api/hooks/useFriendRequest.ts
  src/api/hooks/useTeam.ts
  src/api/hooks/useUserData.ts
  src/assets/dragging.gif
  src/assets/friends.png
  src/assets/icon.png
  src/assets/making.gif
  src/assets/selecting.gif
  src/assets/teamplan.png
  src/assets/teamplan2.png
  src/components/common/AppGuide/AppGuide.styles.ts
  src/components/common/Input/Input.tsx
  src/components/common/Notification/Notification.tsx
  src/components/features/CustomCalendar/CustomCalendar.styles.ts
  src/components/features/CustomCalendar/CustomCalendar.tsx
  src/components/features/DatePicker/DatePicker.tsx
  src/components/features/MicrophoneButton/MicrophoneButton.styles.ts
  src/components/features/MicrophoneButton/MicrophoneButton.tsx
  src/hooks/useNotificationSetup.ts
  src/pages/Friend/FriendDetailPage.tsx
  src/pages/Friend/FriendPage.tsx
  src/pages/Landing/LandingPage.tsx
  src/pages/LoginModal/RedirectPage.tsx
  src/pages/Main/MainPage.tsx
  src/pages/Mypage/Mypage.tsx
  src/pages/Plan/PlanPage.tsx
  src/pages/Plan/PlanSelectPage.tsx
  src/pages/TeamPlan/TeamPlan.tsx
  tsconfig.json
Labels: ✨feature
